name: Release python package

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install deps
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
          python-version: "3.12"
          version: "latest"
      - name: Set verison
        run: uv version "${{ github.ref_name }}"
      - name: Build
        run: uv build
      - name: Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish
